### ISSUE TITLE
Can this implementation be used for non-medical image segmentation?

### ISSUE THREAD

**Issue by ogencoglu** [PengchengShi1220/NexToU#10]
Can this implementation be used for binary segmentation of RGB or grayscale images where structural coherence/integrity and skeletons are very important (e.g. segmenting roads from satellite images).

What is needed to accommodate the code for that purpose?

**Comment by PengchengShi1220** [comment]
Hi,

Thank you for your inquiry. Yes, it is possible. Since NexToU is based on the nnU-Net V2 framework, it supports both RGB and grayscale images, including various image data formats. You can find more details here: [nnUNet dataset format documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md).

For road segmentation datasets, you can refer to the following example: [Dataset120_RoadSegmentation.py](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset120_RoadSegmentation.py). I recommend using the nnU-Net V2 framework for training.

If you prefer not to use the nnU-Net framework, you can still use NexToU. In this case, you will need to modify the network structure to NexToU and manually set the related input parameters. You can find the network architecture details here: [NexToU.py](https://github.com/PengchengShi1220/NexToU/blob/9b7d600491905bc449ae8c51c9e0c763c1d5008d/network_architecture/NexToU.py#L11).

**Comment by ogencoglu** [comment]
Thanks for the swift reply.
